src_dir: src
public_dir: docs

title: Huangxin's Daily Navigation

bookmarks:
  - name: GitHub
    url: https://github.com
    favicon: image.flaticon.com/icons/svg/2111/2111432.svg
  - name: Outlook
    url: https://outlook.com
    favicon: gist.githubusercontent.com/hifocus/651543be58e1842641502c28c44370e3/raw/e20e002aa701f85be1e01b21932309cfa65fa3a5/icons8-microsoft-outlook-2019.svg
  - name: Office 365
    url: https://office.com
    favicon: gist.githubusercontent.com/hifocus/dfa609609226c4c758b0b5d835d1fe5a/raw/f43329eaf0eabde44ad4898bbfe06a2bc0fb571d/office.svg
  - name: Gmail
    url: https://gmail.com
    favicon: image.flaticon.com/icons/svg/281/281769.svg
  - name: YouTube
    url: https://youtube.com
    favicon: image.flaticon.com/icons/svg/1384/1384060.svg

  - category: Connectivity Testing
  - name: IPIP Ping
    url: https://tools.ipip.net/ping.php
    favicon: i.imgur.com/xAvhqHY.png
  - name: IPIP Traceroute
    url: https://tools.ipip.net/traceroute.php
    favicon: i.imgur.com/xAvhqHY.png
  - name: IPIP HTTP Head
    url: https://tools.ipip.net/httphead.php
    favicon: i.imgur.com/xAvhqHY.png
  - name: Chinaz Ping
    url: https://ping.chinaz.com
    favicon: i.imgur.com/ZCAmN3H.png
  - name: 17ce CDN Preload
    url: https://www.17ce.com
    favicon: i.imgur.com/Q35M5zG.png
  - name: CDNPerf Latency Benchmark
    url: https://www.cdnperf.com/tools/cdn-latency-benchmark
    favicon: www.cdnperf.com/img/icon/apple-touch-icon.png
  - name: DNSPerf DNS Speed Benchmark
    url: https://www.dnsperf.com/dns-speed-benchmark/
    favicon: www.dnsperf.com/img/icons/apple-touch-icon.png
  - name: DNSMap
    url: https://dnsmap.io
    favicon: dnsmap.io/icons/apple-touch-icon.png
  - name: G Suite Toolbox
    url: https://toolbox.googleapps.com/apps/main/
    favicon: i.imgur.com/QmWT75I.png
  - name: HTTP Status Code Checker
    url: https://httpstatus.io
    favicon: httpstatus.io/images/favicon.png

  - category: Web Development Related
  - name: IP.SB Lookup
    url: https://ip.sb
    favicon: i.imgur.com/9YJUCNK.png
  - name: IP.SB Whois
    url: https://ip.sb/whois
    favicon: i.imgur.com/9YJUCNK.png
  - name: CIDR & IPv4 Conversion
    url: https://www.ipaddressguide.com/cidr
    favicon: www.ipaddressguide.com/apple-touch-icon.png
  - name: Source Code Beautifier
    url: https://ctrlq.org/beautifier/
    favicon: i.imgur.com/gr9Skwp.png
  - name: HTML Minifier
    url: https://www.willpeavy.com/tools/minifier/
    favicon: i.imgur.com/Zr8YnqV.png

  - category: Sandboxes and Pastebins
  - name: CodeSandbox
    url: https://codesandbox.io/s/
    favicon: image.flaticon.com/user_icons/19089/19089794/1580931599914.svg
  - name: CodePen
    url: https://codepen.io/pen/
    favicon: image.flaticon.com/icons/svg/2111/2111501.svg
  - name: JSFiddle
    url: https://jsfiddle.net
    favicon: image.flaticon.com/user_icons/19089/19089794/1580931146119.svg
  - name: PlayCode
    url: https://playcode.io
    favicon: playcode.io/static/img/favicons/192x192.png
  - name: Laravel Pastebin
    url: https://paste.laravel.io
    favicon: paste.laravel.io/images/favicons/apple-touch-icon.png
  - name: PasteBin.com
    url: https://pastebin.com
    favicon: pastebin.com/i/pastebin_logo_side_outline.png
  - name: Ubuntu Pastebin
    url: https://paste.ubuntu.com
    favicon: image.flaticon.com/user_icons/19089/19089794/1580932078171.svg
  - name: CentOS Pastebin
    url: https://pastebin.centos.org
    favicon: image.flaticon.com/user_icons/19089/19089794/1580932310027.svg
  - name: GitHub Gist
    url: https://gist.github.com
    favicon: image.flaticon.com/icons/svg/2111/2111432.svg
  - name: Paste.to
    url: https://paste.to
    favicon: paste.to/favicon.png

  - category: Colour Pickers
  - name: Flat UI Colors
    url: https://flatuicolors.com
    favicon: flatuicolors.com/static/favicon.ico
  - name: Coolors
    url: https://coolors.co/app
    favicon: coolors.co/assets/images/favicon.png
  - name: Material Deisgn Colors
    url: https://www.materialui.co/colors
    favicon: www.materialui.co/img/favicon.gif
  - name: Brand Colors
    url: https://brandcolors.net
    favicon: brandcolors.net/assets/img/logo.png